project_name: travis-play
release:
  github:
    owner: furdarius
    name: travis-play
  name_template: '{{.Tag}}'
brew:
  commit_author:
    name: Artemiy Ryabinkov
    email: getlag@ya.ru
  install: bin.install "travis-play"
  skip_upload: true
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: travis-play
  env:
    # https://github.com/goreleaser/goreleaser/issues/225
    - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  format_overrides:
    - goos: windows
      format: zip
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  homepage: https://github.com/furdarius/travis-play
  maintainer: Artemiy Ryabinkov <getlag@ya.ru>
  description: Goreleaser usage example.
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/local/bin
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
dockers:
  -
    binary: travis-play
    goos: linux
    goarch: amd64
    goarm: ''
    image: furdarius/travis-play
    tag_templates:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - "v{{ .Major }}.{{ .Minor }}"
    - latest
