language: go

go:
  - '1.9.x'
  - '1.10.x'
  - 'tip'

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - go test -v -race -cpu=1,2 -tags integration -timeout 2s ./...

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    go: '1.10.x'

