sudo: required

language: go

services:
  - docker

go:
  - 1.9.x
  - tip

before_install:
  - gem install --no-ri --no-rdoc fpm
  - go get -u github.com/goreleaser/goreleaser

script:
  - go test -v -race -cpu=1,2 -tags integration -timeout 2s ./...

deploy:
  provider: script
  script: goreleaser
  skip_cleanup: true
  on:
    tags: true
