sudo: required

language: go

services:
  - docker

go:
  - 1.9.x
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - gem install --no-ri --no-rdoc fpm

script:
  - go test -v -race -cpu=1,2 -tags integration -timeout 2s ./...

after_success:
  - test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
