sudo: required

language: go

services:
  - docker

go:
  - 1.9.x
  - tip

before_install:
  - gem install fpm

script:
  - go test -v -race -cpu=1,2 -tags integration -timeout 2s ./...

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  skip_cleanup: true
  on:
    tags: true
